#!/bin/bash
set -e

CERT_SRC="/certs-source/postgres"
CERT_DST="/certs"
POSTGRES_TLS="${POSTGRES_TLS:-off}"

if [ "$POSTGRES_TLS" = "on" ]; then
    # -- Wait for Vault Agent to issue certificates ----------------
    # `-s` ("non-empty") instead of `-f` ("exists"): Vault Agent's
    # first-run template render is multi-step — the file briefly
    # exists with empty/partial content before the final write
    # finishes. Catching it mid-render and copying partial content
    # caused first-init to fail with `could not load root
    # certificate file: no certificate or crl found` from the
    # temp postgres started during initdb, which silently skipped
    # CREATE DATABASE — the volume then stuck in a half-init
    # state forever (cluster present, target DB absent, no
    # recovery without dropping the volume).
    #
    # We also openssl-validate the CA cert: `-s` catches empty
    # files but not truncated mid-PEM ones, and the CA in
    # particular is what the temp-postgres start failed on.
    echo "TLS enabled -- waiting for certificates from Vault Agent..."
    while [ ! -s "$CERT_SRC/postgres.crt" ] || \
          [ ! -s "$CERT_SRC/postgres.key" ] || \
          [ ! -s "$CERT_SRC/ca.crt" ] || \
          ! openssl x509 -in "$CERT_SRC/ca.crt" -noout 2>/dev/null; do
        sleep 1
    done
    echo "Certificates found and CA validated."

    # -- Copy certs with correct ownership -------------------------
    # PostgreSQL requires key files owned by uid 70 (postgres) with 0600
    mkdir -p "$CERT_DST"
    cp "$CERT_SRC/postgres.crt" "$CERT_DST/server.crt"
    cp "$CERT_SRC/postgres.key" "$CERT_DST/server.key"
    cp "$CERT_SRC/ca.crt"       "$CERT_DST/ca.crt"

    # Copy CA to the location psql client expects
    mkdir -p /root/.postgresql
    cp "$CERT_SRC/ca.crt"       "/root/.postgresql/root.crt"

    chown 70:70 "$CERT_DST/server.crt" "$CERT_DST/server.key" "$CERT_DST/ca.crt"
    chmod 0600  "$CERT_DST/server.key"
    chmod 0644  "$CERT_DST/server.crt" "$CERT_DST/ca.crt"

    echo "Certificates loaded: server.crt, server.key, ca.crt"

    # -- Generate pg_hba.conf that forces TLS on TCP ---------------
    # hostssl = only allow TLS connections over TCP
    # local   = Unix socket (no TLS needed, same-container only)
    PG_HBA="$CERT_DST/pg_hba.conf"
    cat > "$PG_HBA" <<'EOF'
# TYPE    DATABASE  USER  ADDRESS    METHOD
local     all       all              trust
hostssl   all       all   0.0.0.0/0  scram-sha-256
hostssl   all       all   ::0/0      scram-sha-256
EOF
    chown 70:70 "$PG_HBA"

    echo "TLS enforced -- plain TCP connections will be rejected."

    # Start certificate watcher in background for auto-reload on renewal
    /usr/local/bin/cert-watcher.sh &

    # -- Start PostgreSQL with TLS flags ---------------------------
    # Defense-in-depth alongside the cert validity check above:
    # when the data directory is empty, the official postgres
    # entrypoint runs initdb + a temporary postgres for setup SQL
    # (CREATE DATABASE, CREATE USER, etc.). That temp postgres
    # inherits any `-c` flags we pass, including ssl_*. If the CA
    # file is even briefly bad, the temp postgres dies, the setup
    # SQL is silently skipped, and the volume is forever stuck
    # in a half-init state.
    #
    # Avoid the entire class of failure by writing SSL config into
    # postgresql.auto.conf (which the real postgres reads on
    # start) and writing pg_hba.conf via PGDATA, rather than
    # passing them as command-line flags. That way the temp
    # postgres uses defaults during init and SSL only kicks in for
    # the real, post-init server start. If init has already
    # happened (PG_VERSION exists), we fall back to the flag-based
    # path — postgresql.auto.conf is already populated from a
    # prior run, so passing flags too is harmless.
    PGDATA_DIR="${PGDATA:-/var/lib/postgresql/data}"
    if [ ! -s "$PGDATA_DIR/PG_VERSION" ]; then
        # First-run path: stage SSL config into the data dir AFTER
        # the official entrypoint runs initdb + setup SQL but
        # BEFORE the real postgres start. Use the entrypoint's
        # /docker-entrypoint-initdb.d/ hook for that.
        mkdir -p /docker-entrypoint-initdb.d
        cat > /docker-entrypoint-initdb.d/zz-tls.sh <<'EOSH'
#!/bin/bash
# Auto-generated by docker-entrypoint-tls.sh on first init.
# Writes SSL config into postgresql.auto.conf so the real
# postgres start (after this script and other initdb.d scripts
# finish) picks them up.
set -e
cat >> "$PGDATA/postgresql.auto.conf" <<'EOC'
ssl = on
ssl_cert_file = '/certs/server.crt'
ssl_key_file = '/certs/server.key'
ssl_ca_file = '/certs/ca.crt'
hba_file = '/certs/pg_hba.conf'
EOC
EOSH
        chmod +x /docker-entrypoint-initdb.d/zz-tls.sh
        exec docker-entrypoint.sh "$@"
    fi

    # Already-initialized path: data dir has a PG_VERSION marker,
    # so no temp postgres will be started. Safe to pass SSL flags
    # directly. (Kept for back-compat with volumes that pre-date
    # the postgresql.auto.conf approach above.)
    exec docker-entrypoint.sh "$@" \
        -c ssl=on \
        -c ssl_cert_file=/certs/server.crt \
        -c ssl_key_file=/certs/server.key \
        -c ssl_ca_file=/certs/ca.crt \
        -c hba_file=/certs/pg_hba.conf
else
    echo "TLS disabled -- starting PostgreSQL without SSL."
    exec docker-entrypoint.sh "$@"
fi
