# preserve upstream forwarding headers
map $http_x_forwarded_proto $forwarded_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

server {
    listen 8280 default_server;

    resolver 127.0.0.11 valid=30s;

    location ~ ^/v1/[^/]+/crt(/pem)?$ {
        proxy_pass http://vault.akashic.local:8281;
        proxy_set_header Host $host;
    }

    location ~ ^/v1/[^/]+/ca(/pem)?$ {
        proxy_pass http://vault.akashic.local:8281;
        proxy_set_header Host $host;
    }
}
