package cmd

import (
	"akashic/akashic/pkg/cli/core"

	"github.com/spf13/cobra"
)

func NewEngineSignIntermediateCmd(ctx *core.CliContext) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "intermediate",
		Short: "Sign an intermediate CA CSR",
		Long: `Sign an intermediate CA Certificate Signing Request using a parent PKI engine.

The signing engine (--engine / -e) is the parent CA that will sign the CSR.
The CSR file (--csr) is the PEM-encoded CSR generated by the intermediate engine.
The signed certificate is written to the output file (--output / -o).

Configuration is merged from four sources (lowest to highest priority):
  1. Defaults: use_csr_values=true, format=pem_bundle, ttl=43800h (5yr)
  2. Config file (--config-file / -f): overrides matching fields
  3. Inline config (--config): overrides matching fields
  4. --cn flag: overrides common_name from any source`,
		Args: cobra.NoArgs,
		RunE: ctx.RunPkiVaultEngineSignIntermediateCmd,
	}

	core.RegisterFlags(cmd, core.FilterCliConfig(
		core.Secret,
		core.SecretPath,
		core.VaultRootTokenFile,
		core.EngineConfigFile,
		core.EngineConfig,
		core.EngineName,
		core.CsrOutput,
		core.CsrCommonName,
		core.SignCsrInput,
	)...)

	return cmd
}
